<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class GiangVienSeeder extends Seeder
{
    public function run(): void
    {
        // Lấy ID các khoa
        $khoaCNTT = DB::table('khoa')->where('ten_khoa', 'LIKE', '%Công nghệ thông tin%')->value('id');
        $khoaKT = DB::table('khoa')->where('ten_khoa', 'LIKE', '%Kinh tế%')->value('id');
        $khoaNN = DB::table('khoa')->where('ten_khoa', 'LIKE', '%Ngoại ngữ%')->value('id');

        if (!$khoaCNTT || !$khoaKT || !$khoaNN) {
            echo "❌ Không tìm thấy đủ các khoa\n";
            return;
        }

        // Lấy ID trình độ
        $trinhDoTS = DB::table('dm_trinh_do')->where('ten_trinh_do', 'Tiến sĩ')->value('id');
        $trinhDoThS = DB::table('dm_trinh_do')->where('ten_trinh_do', 'Thạc sĩ')->value('id');

        if (!$trinhDoTS || !$trinhDoThS) {
            echo "❌ Không tìm thấy trình độ Tiến sĩ hoặc Thạc sĩ\n";
            return;
        }

        // Lấy ID vai trò giảng viên
        $vaiTroGiangVien = DB::table('vai_tro')->where('ten_vai_tro', 'Giảng viên')->value('id');

        if (!$vaiTroGiangVien) {
            echo "❌ Không tìm thấy vai trò Giảng viên\n";
            return;
        }

        // Lấy danh sách môn học để map
        $allMonHocs = DB::table('mon_hoc')->select('id', 'ma_mon', 'ten_mon')->get();

        // Helper function để tìm môn học theo tên
        $findMonHoc = function ($keywords) use ($allMonHocs) {
            $ids = [];
            foreach ($keywords as $keyword) {
                foreach ($allMonHocs as $mh) {
                    if (stripos($mh->ten_mon, $keyword) !== false || stripos($mh->ma_mon, $keyword) !== false) {
                        $ids[] = $mh->id;
                    }
                }
            }
            return array_unique($ids);
        };

        // Danh sách giảng viên với môn học mapping
        $giangViens = [
            // Khoa Công nghệ thông tin (10 người)
            [
                'ma_giang_vien' => 'GV001',
                'ho_ten' => 'Nguyễn Văn An',
                'gioi_tinh' => 'Nam',
                'ngay_sinh' => '1985-03-15',
                'dia_chi' => 'Hà Nội',
                'email' => 'nva.gv@university.edu.vn',
                'so_dien_thoai' => '0901234561',
                'khoa_id' => $khoaCNTT,
                'trinh_do_id' => $trinhDoTS,
                'mon_hoc_keywords' => ['Lập trình Web', 'Cơ sở dữ liệu', 'HTML', 'CSS', 'JavaScript', 'PHP', 'Laravel'],
                'ngay_vao_truong' => '2015-09-01',
            ],
            [
                'ma_giang_vien' => 'GV002',
                'ho_ten' => 'Trần Thị Bích',
                'gioi_tinh' => 'Nữ',
                'ngay_sinh' => '1987-07-22',
                'dia_chi' => 'TP.HCM',
                'email' => 'ttb.gv@university.edu.vn',
                'so_dien_thoai' => '0901234562',
                'khoa_id' => $khoaCNTT,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Java', 'Lập trình hướng đối tượng'],
                'ngay_vao_truong' => '2017-03-15',
            ],
            [
                'ma_giang_vien' => 'GV003',
                'ho_ten' => 'Lê Minh Cường',
                'gioi_tinh' => 'Nam',
                'ngay_sinh' => '1988-11-10',
                'dia_chi' => 'Đà Nẵng',
                'email' => 'lmc.gv@university.edu.vn',
                'so_dien_thoai' => '0901234563',
                'khoa_id' => $khoaCNTT,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Phát triển ứng dụng', 'Công nghệ phần mềm'],
                'ngay_vao_truong' => '2018-08-20',
            ],
            [
                'ma_giang_vien' => 'GV004',
                'ho_ten' => 'Phạm Văn Dũng',
                'gioi_tinh' => 'Nam',
                'ngay_sinh' => '1984-05-18',
                'dia_chi' => 'Hà Nội',
                'email' => 'pvd.gv@university.edu.vn',
                'so_dien_thoai' => '0901234564',
                'khoa_id' => $khoaCNTT,
                'trinh_do_id' => $trinhDoTS,
                'mon_hoc_keywords' => ['Trí tuệ nhân tạo', 'Machine Learning', 'Học máy'],
                'ngay_vao_truong' => '2014-01-10',
            ],
            [
                'ma_giang_vien' => 'GV005',
                'ho_ten' => 'Hoàng Thị Em',
                'gioi_tinh' => 'Nữ',
                'ngay_sinh' => '1986-09-25',
                'dia_chi' => 'TP.HCM',
                'email' => 'hte.gv@university.edu.vn',
                'so_dien_thoai' => '0901234565',
                'khoa_id' => $khoaCNTT,
                'trinh_do_id' => $trinhDoTS,
                'mon_hoc_keywords' => ['Khoa học dữ liệu', 'Big Data', 'Phân tích dữ liệu'],
                'ngay_vao_truong' => '2016-06-05',
            ],
            [
                'ma_giang_vien' => 'GV006',
                'ho_ten' => 'Đỗ Văn Phong',
                'gioi_tinh' => 'Nam',
                'ngay_sinh' => '1990-04-12',
                'dia_chi' => 'Hải Phòng',
                'email' => 'dvp.gv@university.edu.vn',
                'so_dien_thoai' => '0901234566',
                'khoa_id' => $khoaCNTT,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Thuật toán', 'Cấu trúc dữ liệu', 'Toán rời rạc'],
                'ngay_vao_truong' => '2019-02-14',
            ],
            [
                'ma_giang_vien' => 'GV007',
                'ho_ten' => 'Vũ Thị Giang',
                'gioi_tinh' => 'Nữ',
                'ngay_sinh' => '1991-08-30',
                'dia_chi' => 'Cần Thơ',
                'email' => 'vtg.gv@university.edu.vn',
                'so_dien_thoai' => '0901234567',
                'khoa_id' => $khoaCNTT,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Học sâu', 'Neural Network', 'Deep Learning'],
                'ngay_vao_truong' => '2020-09-01',
            ],
            [
                'ma_giang_vien' => 'GV008',
                'ho_ten' => 'Bùi Văn Hải',
                'gioi_tinh' => 'Nam',
                'ngay_sinh' => '1986-02-28',
                'dia_chi' => 'Hà Nội',
                'email' => 'bvh.gv@university.edu.vn',
                'so_dien_thoai' => '0901234568',
                'khoa_id' => $khoaCNTT,
                'trinh_do_id' => $trinhDoTS,
                'mon_hoc_keywords' => ['Mật mã', 'An toàn', 'Bảo mật'],
                'ngay_vao_truong' => '2015-04-20',
            ],
            [
                'ma_giang_vien' => 'GV009',
                'ho_ten' => 'Ngô Thị Hoa',
                'gioi_tinh' => 'Nữ',
                'ngay_sinh' => '1989-06-18',
                'dia_chi' => 'TP.HCM',
                'email' => 'nth.gv@university.edu.vn',
                'so_dien_thoai' => '0901234569',
                'khoa_id' => $khoaCNTT,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['An ninh mạng', 'Bảo mật hệ thống'],
                'ngay_vao_truong' => '2018-11-12',
            ],
            [
                'ma_giang_vien' => 'GV010',
                'ho_ten' => 'Đinh Văn Khải',
                'gioi_tinh' => 'Nam',
                'ngay_sinh' => '1992-01-05',
                'dia_chi' => 'Đà Nẵng',
                'email' => 'dvk.gv@university.edu.vn',
                'so_dien_thoai' => '0901234570',
                'khoa_id' => $khoaCNTT,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Kiểm thử', 'Bảo mật'],
                'ngay_vao_truong' => '2021-01-15',
            ],

            // Khoa Kinh tế (11 người)
            [
                'ma_giang_vien' => 'GV011',
                'ho_ten' => 'Lý Văn Long',
                'gioi_tinh' => 'Nam',
                'ngay_sinh' => '1984-03-20',
                'dia_chi' => 'Hà Nội',
                'email' => 'lvl.gv@university.edu.vn',
                'so_dien_thoai' => '0901234571',
                'khoa_id' => $khoaKT,
                'trinh_do_id' => $trinhDoTS,
                'mon_hoc_keywords' => ['Quản trị', 'Marketing', 'Chiến lược'],
                'ngay_vao_truong' => '2013-09-01',
            ],
            [
                'ma_giang_vien' => 'GV012',
                'ho_ten' => 'Phan Thị Mai',
                'gioi_tinh' => 'Nữ',
                'ngay_sinh' => '1987-11-14',
                'dia_chi' => 'TP.HCM',
                'email' => 'ptm.gv@university.edu.vn',
                'so_dien_thoai' => '0901234572',
                'khoa_id' => $khoaKT,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Nhân sự', 'Hành vi tổ chức', 'Quản trị'],
                'ngay_vao_truong' => '2016-03-10',
            ],
            [
                'ma_giang_vien' => 'GV013',
                'ho_ten' => 'Võ Văn Nam',
                'gioi_tinh' => 'Nam',
                'ngay_sinh' => '1988-05-08',
                'dia_chi' => 'Đà Nẵng',
                'email' => 'vvn.gv@university.edu.vn',
                'so_dien_thoai' => '0901234573',
                'khoa_id' => $khoaKT,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Kinh doanh quốc tế', 'Logistics'],
                'ngay_vao_truong' => '2017-07-05',
            ],
            [
                'ma_giang_vien' => 'GV014',
                'ho_ten' => 'Đặng Thị Oanh',
                'gioi_tinh' => 'Nữ',
                'ngay_sinh' => '1990-09-12',
                'dia_chi' => 'Hải Phòng',
                'email' => 'dto.gv@university.edu.vn',
                'so_dien_thoai' => '0901234574',
                'khoa_id' => $khoaKT,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Quản trị dự án', 'Quản trị'],
                'ngay_vao_truong' => '2019-01-20',
            ],
            [
                'ma_giang_vien' => 'GV015',
                'ho_ten' => 'Trịnh Văn Phúc',
                'gioi_tinh' => 'Nam',
                'ngay_sinh' => '1985-07-25',
                'dia_chi' => 'Cần Thơ',
                'email' => 'tvp.gv@university.edu.vn',
                'so_dien_thoai' => '0901234575',
                'khoa_id' => $khoaKT,
                'trinh_do_id' => $trinhDoTS,
                'mon_hoc_keywords' => ['Tài chính', 'Đầu tư', 'Ngân hàng'],
                'ngay_vao_truong' => '2014-05-15',
            ],
            [
                'ma_giang_vien' => 'GV016',
                'ho_ten' => 'Cao Thị Quỳnh',
                'gioi_tinh' => 'Nữ',
                'ngay_sinh' => '1989-12-03',
                'dia_chi' => 'Hà Nội',
                'email' => 'ctq.gv@university.edu.vn',
                'so_dien_thoai' => '0901234576',
                'khoa_id' => $khoaKT,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Ngân hàng'],
                'ngay_vao_truong' => '2018-02-28',
            ],
            [
                'ma_giang_vien' => 'GV017',
                'ho_ten' => 'Hồ Văn Rộng',
                'gioi_tinh' => 'Nam',
                'ngay_sinh' => '1991-04-16',
                'dia_chi' => 'TP.HCM',
                'email' => 'hvr.gv@university.edu.vn',
                'so_dien_thoai' => '0901234577',
                'khoa_id' => $khoaKT,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Chứng khoán', 'Tài chính'],
                'ngay_vao_truong' => '2020-06-10',
            ],
            [
                'ma_giang_vien' => 'GV018',
                'ho_ten' => 'Lương Văn Sơn',
                'gioi_tinh' => 'Nam',
                'ngay_sinh' => '1986-10-22',
                'dia_chi' => 'Đà Nẵng',
                'email' => 'lvs.gv@university.edu.vn',
                'so_dien_thoai' => '0901234578',
                'khoa_id' => $khoaKT,
                'trinh_do_id' => $trinhDoTS,
                'mon_hoc_keywords' => ['Kế toán', 'Kiểm toán'],
                'ngay_vao_truong' => '2015-09-01',
            ],
            [
                'ma_giang_vien' => 'GV019',
                'ho_ten' => 'Dương Thị Tâm',
                'gioi_tinh' => 'Nữ',
                'ngay_sinh' => '1988-08-17',
                'dia_chi' => 'Hải Phòng',
                'email' => 'dtt.gv@university.edu.vn',
                'so_dien_thoai' => '0901234579',
                'khoa_id' => $khoaKT,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Kế toán'],
                'ngay_vao_truong' => '2017-11-05',
            ],
            [
                'ma_giang_vien' => 'GV020',
                'ho_ten' => 'Ông Văn Út',
                'gioi_tinh' => 'Nam',
                'ngay_sinh' => '1990-02-28',
                'dia_chi' => 'Cần Thơ',
                'email' => 'ovu.gv@university.edu.vn',
                'so_dien_thoai' => '0901234580',
                'khoa_id' => $khoaKT,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Thuế', 'Kế toán'],
                'ngay_vao_truong' => '2019-04-22',
            ],
            [
                'ma_giang_vien' => 'GV021',
                'ho_ten' => 'Mai Thị Vân',
                'gioi_tinh' => 'Nữ',
                'ngay_sinh' => '1992-05-06',
                'dia_chi' => 'Hà Nội',
                'email' => 'mtv.gv@university.edu.vn',
                'so_dien_thoai' => '0901234581',
                'khoa_id' => $khoaKT,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Kế toán', 'Ngân hàng'],
                'ngay_vao_truong' => '2021-08-30',
            ],

            // Khoa Ngoại ngữ (9 người)
            [
                'ma_giang_vien' => 'GV022',
                'ho_ten' => 'Nguyễn Thị Xuân',
                'gioi_tinh' => 'Nữ',
                'ngay_sinh' => '1985-12-10',
                'dia_chi' => 'TP.HCM',
                'email' => 'ntx.gv@university.edu.vn',
                'so_dien_thoai' => '0901234582',
                'khoa_id' => $khoaNN,
                'trinh_do_id' => $trinhDoTS,
                'mon_hoc_keywords' => ['Tiếng Anh', 'Anh'],
                'ngay_vao_truong' => '2014-09-01',
            ],
            [
                'ma_giang_vien' => 'GV023',
                'ho_ten' => 'Trần Văn Yên',
                'gioi_tinh' => 'Nam',
                'ngay_sinh' => '1987-03-28',
                'dia_chi' => 'Đà Nẵng',
                'email' => 'tvy.gv@university.edu.vn',
                'so_dien_thoai' => '0901234583',
                'khoa_id' => $khoaNN,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Văn học', 'Dịch thuật', 'Anh'],
                'ngay_vao_truong' => '2016-02-15',
            ],
            [
                'ma_giang_vien' => 'GV024',
                'ho_ten' => 'Lê Thị Ánh',
                'gioi_tinh' => 'Nữ',
                'ngay_sinh' => '1989-07-19',
                'dia_chi' => 'Hải Phòng',
                'email' => 'lta.gv@university.edu.vn',
                'so_dien_thoai' => '0901234584',
                'khoa_id' => $khoaNN,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Tiếng Anh', 'Giao tiếp'],
                'ngay_vao_truong' => '2018-05-20',
            ],
            [
                'ma_giang_vien' => 'GV025',
                'ho_ten' => 'Phạm Văn Bình',
                'gioi_tinh' => 'Nam',
                'ngay_sinh' => '1986-01-15',
                'dia_chi' => 'Cần Thơ',
                'email' => 'pvb.gv@university.edu.vn',
                'so_dien_thoai' => '0901234585',
                'khoa_id' => $khoaNN,
                'trinh_do_id' => $trinhDoTS,
                'mon_hoc_keywords' => ['Tiếng Nhật', 'Nhật'],
                'ngay_vao_truong' => '2015-03-10',
            ],
            [
                'ma_giang_vien' => 'GV026',
                'ho_ten' => 'Hoàng Thị Cẩm',
                'gioi_tinh' => 'Nữ',
                'ngay_sinh' => '1988-11-24',
                'dia_chi' => 'Hà Nội',
                'email' => 'htc.gv@university.edu.vn',
                'so_dien_thoai' => '0901234586',
                'khoa_id' => $khoaNN,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Tiếng Nhật', 'Giao tiếp'],
                'ngay_vao_truong' => '2017-09-05',
            ],
            [
                'ma_giang_vien' => 'GV027',
                'ho_ten' => 'Đỗ Văn Đạt',
                'gioi_tinh' => 'Nam',
                'ngay_sinh' => '1990-06-09',
                'dia_chi' => 'TP.HCM',
                'email' => 'dvd.gv@university.edu.vn',
                'so_dien_thoai' => '0901234587',
                'khoa_id' => $khoaNN,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Dịch thuật', 'Nhật', 'Kinh doanh'],
                'ngay_vao_truong' => '2019-06-15',
            ],
            [
                'ma_giang_vien' => 'GV028',
                'ho_ten' => 'Vũ Văn Gia',
                'gioi_tinh' => 'Nam',
                'ngay_sinh' => '1987-09-13',
                'dia_chi' => 'Đà Nẵng',
                'email' => 'vvg.gv@university.edu.vn',
                'so_dien_thoai' => '0901234588',
                'khoa_id' => $khoaNN,
                'trinh_do_id' => $trinhDoTS,
                'mon_hoc_keywords' => ['Tiếng Trung', 'Văn học', 'Hán'],
                'ngay_vao_truong' => '2016-01-20',
            ],
            [
                'ma_giang_vien' => 'GV029',
                'ho_ten' => 'Bùi Thị Hạnh',
                'gioi_tinh' => 'Nữ',
                'ngay_sinh' => '1989-04-21',
                'dia_chi' => 'Hải Phòng',
                'email' => 'bth.gv@university.edu.vn',
                'so_dien_thoai' => '0901234589',
                'khoa_id' => $khoaNN,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Tiếng Trung', 'Giao tiếp'],
                'ngay_vao_truong' => '2018-08-25',
            ],
            [
                'ma_giang_vien' => 'GV030',
                'ho_ten' => 'Ngô Văn Khánh',
                'gioi_tinh' => 'Nam',
                'ngay_sinh' => '1991-10-30',
                'dia_chi' => 'Cần Thơ',
                'email' => 'nvk.gv@university.edu.vn',
                'so_dien_thoai' => '0901234590',
                'khoa_id' => $khoaNN,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Thương mại', 'Trung', 'Dịch thuật'],
                'ngay_vao_truong' => '2020-10-01',
            ],
            // Giảng viên test
            [
                'ma_giang_vien' => 'GV031',
                'ho_ten' => 'Giảng Viên Test',
                'gioi_tinh' => 'Nam',
                'ngay_sinh' => '1985-01-01',
                'dia_chi' => 'Hà Nội',
                'email' => 'giangvien@sis.edu.vn',
                'so_dien_thoai' => '0901234591',
                'khoa_id' => $khoaCNTT,
                'trinh_do_id' => $trinhDoTS,
                'mon_hoc_keywords' => ['Lập trình Web', 'Cơ sở dữ liệu'],
                'ngay_vao_truong' => '2015-09-01',
            ],

            // ========== THÊM GIẢNG VIÊN ĐỂ ĐỦ CHO TẤT CẢ MÔN HỌC ==========
            // Khoa CNTT - Thêm 10 giảng viên (GV032 - GV041)
            [
                'ma_giang_vien' => 'GV032',
                'ho_ten' => 'Trần Văn Linh',
                'gioi_tinh' => 'Nam',
                'ngay_sinh' => '1987-02-14',
                'dia_chi' => 'Hà Nội',
                'email' => 'tvl.gv@university.edu.vn',
                'so_dien_thoai' => '0901234592',
                'khoa_id' => $khoaCNTT,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Công nghệ phần mềm', 'Phát triển ứng dụng'],
                'ngay_vao_truong' => '2016-03-15',
            ],
            [
                'ma_giang_vien' => 'GV033',
                'ho_ten' => 'Lê Thị Mỹ',
                'gioi_tinh' => 'Nữ',
                'ngay_sinh' => '1989-05-20',
                'dia_chi' => 'TP.HCM',
                'email' => 'ltm.gv@university.edu.vn',
                'so_dien_thoai' => '0901234593',
                'khoa_id' => $khoaCNTT,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Phát triển ứng dụng Web', 'Lập trình Web'],
                'ngay_vao_truong' => '2017-08-20',
            ],
            [
                'ma_giang_vien' => 'GV034',
                'ho_ten' => 'Phạm Văn Nghĩa',
                'gioi_tinh' => 'Nam',
                'ngay_sinh' => '1990-07-08',
                'dia_chi' => 'Đà Nẵng',
                'email' => 'pvn.gv@university.edu.vn',
                'so_dien_thoai' => '0901234594',
                'khoa_id' => $khoaCNTT,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Lập trình di động', 'Mobile'],
                'ngay_vao_truong' => '2018-11-10',
            ],
            [
                'ma_giang_vien' => 'GV035',
                'ho_ten' => 'Hoàng Thị Oanh',
                'gioi_tinh' => 'Nữ',
                'ngay_sinh' => '1991-09-15',
                'dia_chi' => 'Hải Phòng',
                'email' => 'hto.gv@university.edu.vn',
                'so_dien_thoai' => '0901234595',
                'khoa_id' => $khoaCNTT,
                'trinh_do_id' => $trinhDoTS,
                'mon_hoc_keywords' => ['Trí tuệ nhân tạo', 'AI'],
                'ngay_vao_truong' => '2019-02-25',
            ],
            [
                'ma_giang_vien' => 'GV036',
                'ho_ten' => 'Đỗ Văn Phú',
                'gioi_tinh' => 'Nam',
                'ngay_sinh' => '1988-12-22',
                'dia_chi' => 'Cần Thơ',
                'email' => 'dvp2.gv@university.edu.vn',
                'so_dien_thoai' => '0901234596',
                'khoa_id' => $khoaCNTT,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Machine Learning', 'Học máy'],
                'ngay_vao_truong' => '2017-05-12',
            ],
            [
                'ma_giang_vien' => 'GV037',
                'ho_ten' => 'Vũ Thị Quỳnh',
                'gioi_tinh' => 'Nữ',
                'ngay_sinh' => '1992-03-18',
                'dia_chi' => 'Hà Nội',
                'email' => 'vtq.gv@university.edu.vn',
                'so_dien_thoai' => '0901234597',
                'khoa_id' => $khoaCNTT,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Khoa học dữ liệu', 'Data Science'],
                'ngay_vao_truong' => '2020-07-08',
            ],
            [
                'ma_giang_vien' => 'GV038',
                'ho_ten' => 'Bùi Văn Sơn',
                'gioi_tinh' => 'Nam',
                'ngay_sinh' => '1986-06-30',
                'dia_chi' => 'TP.HCM',
                'email' => 'bvs.gv@university.edu.vn',
                'so_dien_thoai' => '0901234598',
                'khoa_id' => $khoaCNTT,
                'trinh_do_id' => $trinhDoTS,
                'mon_hoc_keywords' => ['An toàn bảo mật hệ thống', 'Bảo mật'],
                'ngay_vao_truong' => '2015-10-15',
            ],
            [
                'ma_giang_vien' => 'GV039',
                'ho_ten' => 'Ngô Thị Tuyết',
                'gioi_tinh' => 'Nữ',
                'ngay_sinh' => '1989-11-25',
                'dia_chi' => 'Đà Nẵng',
                'email' => 'ntt.gv@university.edu.vn',
                'so_dien_thoai' => '0901234599',
                'khoa_id' => $khoaCNTT,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Mật mã học', 'Bảo mật'],
                'ngay_vao_truong' => '2018-04-20',
            ],
            [
                'ma_giang_vien' => 'GV040',
                'ho_ten' => 'Đinh Văn Uyên',
                'gioi_tinh' => 'Nam',
                'ngay_sinh' => '1990-08-12',
                'dia_chi' => 'Hải Phòng',
                'email' => 'dvu.gv@university.edu.vn',
                'so_dien_thoai' => '0901234600',
                'khoa_id' => $khoaCNTT,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['IoT', 'Cloud Computing', 'Blockchain'],
                'ngay_vao_truong' => '2019-09-05',
            ],
            [
                'ma_giang_vien' => 'GV041',
                'ho_ten' => 'Lý Thị Vân',
                'gioi_tinh' => 'Nữ',
                'ngay_sinh' => '1991-04-28',
                'dia_chi' => 'Cần Thơ',
                'email' => 'ltv.gv@university.edu.vn',
                'so_dien_thoai' => '0901234601',
                'khoa_id' => $khoaCNTT,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Thực tập', 'Đồ án tốt nghiệp'],
                'ngay_vao_truong' => '2020-12-10',
            ],

            // Khoa Kinh tế - Thêm 10 giảng viên (GV042 - GV051)
            [
                'ma_giang_vien' => 'GV042',
                'ho_ten' => 'Phan Văn Anh',
                'gioi_tinh' => 'Nam',
                'ngay_sinh' => '1987-01-16',
                'dia_chi' => 'Hà Nội',
                'email' => 'pva.gv@university.edu.vn',
                'so_dien_thoai' => '0901234602',
                'khoa_id' => $khoaKT,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Ngân hàng thương mại', 'Ngân hàng'],
                'ngay_vao_truong' => '2016-06-20',
            ],
            [
                'ma_giang_vien' => 'GV043',
                'ho_ten' => 'Võ Thị Bích',
                'gioi_tinh' => 'Nữ',
                'ngay_sinh' => '1989-03-22',
                'dia_chi' => 'TP.HCM',
                'email' => 'vtb.gv@university.edu.vn',
                'so_dien_thoai' => '0901234603',
                'khoa_id' => $khoaKT,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Thanh toán quốc tế', 'Tài chính'],
                'ngay_vao_truong' => '2017-11-15',
            ],
            [
                'ma_giang_vien' => 'GV044',
                'ho_ten' => 'Đặng Văn Cường',
                'gioi_tinh' => 'Nam',
                'ngay_sinh' => '1990-05-08',
                'dia_chi' => 'Đà Nẵng',
                'email' => 'dvc.gv@university.edu.vn',
                'so_dien_thoai' => '0901234604',
                'khoa_id' => $khoaKT,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Kế toán tài chính', 'Kế toán'],
                'ngay_vao_truong' => '2018-08-25',
            ],
            [
                'ma_giang_vien' => 'GV045',
                'ho_ten' => 'Trịnh Thị Dung',
                'gioi_tinh' => 'Nữ',
                'ngay_sinh' => '1991-07-14',
                'dia_chi' => 'Hải Phòng',
                'email' => 'ttd.gv@university.edu.vn',
                'so_dien_thoai' => '0901234605',
                'khoa_id' => $khoaKT,
                'trinh_do_id' => $trinhDoTS,
                'mon_hoc_keywords' => ['Kiểm toán', 'Kế toán'],
                'ngay_vao_truong' => '2019-03-10',
            ],
            [
                'ma_giang_vien' => 'GV046',
                'ho_ten' => 'Cao Văn Đức',
                'gioi_tinh' => 'Nam',
                'ngay_sinh' => '1988-09-26',
                'dia_chi' => 'Cần Thơ',
                'email' => 'cvd.gv@university.edu.vn',
                'so_dien_thoai' => '0901234606',
                'khoa_id' => $khoaKT,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Thương mại điện tử', 'Marketing'],
                'ngay_vao_truong' => '2017-12-05',
            ],
            [
                'ma_giang_vien' => 'GV047',
                'ho_ten' => 'Hồ Thị Hạnh',
                'gioi_tinh' => 'Nữ',
                'ngay_sinh' => '1992-02-19',
                'dia_chi' => 'Hà Nội',
                'email' => 'hth.gv@university.edu.vn',
                'so_dien_thoai' => '0901234607',
                'khoa_id' => $khoaKT,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Thực tập', 'Kinh tế'],
                'ngay_vao_truong' => '2020-10-20',
            ],
            [
                'ma_giang_vien' => 'GV048',
                'ho_ten' => 'Lương Văn Hùng',
                'gioi_tinh' => 'Nam',
                'ngay_sinh' => '1986-12-03',
                'dia_chi' => 'TP.HCM',
                'email' => 'lvh.gv@university.edu.vn',
                'so_dien_thoai' => '0901234608',
                'khoa_id' => $khoaKT,
                'trinh_do_id' => $trinhDoTS,
                'mon_hoc_keywords' => ['Khóa luận tốt nghiệp', 'Kinh tế'],
                'ngay_vao_truong' => '2015-07-15',
            ],
            [
                'ma_giang_vien' => 'GV049',
                'ho_ten' => 'Dương Thị Lan',
                'gioi_tinh' => 'Nữ',
                'ngay_sinh' => '1989-06-11',
                'dia_chi' => 'Đà Nẵng',
                'email' => 'dtl.gv@university.edu.vn',
                'so_dien_thoai' => '0901234609',
                'khoa_id' => $khoaKT,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Quản trị', 'Marketing'],
                'ngay_vao_truong' => '2018-01-30',
            ],
            [
                'ma_giang_vien' => 'GV050',
                'ho_ten' => 'Ông Văn Minh',
                'gioi_tinh' => 'Nam',
                'ngay_sinh' => '1990-10-27',
                'dia_chi' => 'Hải Phòng',
                'email' => 'ovm.gv@university.edu.vn',
                'so_dien_thoai' => '0901234610',
                'khoa_id' => $khoaKT,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Tài chính', 'Ngân hàng'],
                'ngay_vao_truong' => '2019-05-18',
            ],
            [
                'ma_giang_vien' => 'GV051',
                'ho_ten' => 'Mai Thị Nga',
                'gioi_tinh' => 'Nữ',
                'ngay_sinh' => '1991-08-05',
                'dia_chi' => 'Cần Thơ',
                'email' => 'mtn.gv@university.edu.vn',
                'so_dien_thoai' => '0901234611',
                'khoa_id' => $khoaKT,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Kế toán', 'Thuế'],
                'ngay_vao_truong' => '2020-11-12',
            ],

            // Khoa Ngoại ngữ - Thêm 10 giảng viên (GV052 - GV061)
            [
                'ma_giang_vien' => 'GV052',
                'ho_ten' => 'Nguyễn Văn Phong',
                'gioi_tinh' => 'Nam',
                'ngay_sinh' => '1987-04-13',
                'dia_chi' => 'Hà Nội',
                'email' => 'nvp.gv@university.edu.vn',
                'so_dien_thoai' => '0901234612',
                'khoa_id' => $khoaNN,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Kỹ thuật biên dịch', 'Dịch thuật'],
                'ngay_vao_truong' => '2016-09-20',
            ],
            [
                'ma_giang_vien' => 'GV053',
                'ho_ten' => 'Trần Thị Quỳnh',
                'gioi_tinh' => 'Nữ',
                'ngay_sinh' => '1989-06-17',
                'dia_chi' => 'TP.HCM',
                'email' => 'ttq.gv@university.edu.vn',
                'so_dien_thoai' => '0901234613',
                'khoa_id' => $khoaNN,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Kỹ thuật phiên dịch', 'Dịch thuật'],
                'ngay_vao_truong' => '2017-12-10',
            ],
            [
                'ma_giang_vien' => 'GV054',
                'ho_ten' => 'Lê Văn Sơn',
                'gioi_tinh' => 'Nam',
                'ngay_sinh' => '1990-08-24',
                'dia_chi' => 'Đà Nẵng',
                'email' => 'lvs2.gv@university.edu.vn',
                'so_dien_thoai' => '0901234614',
                'khoa_id' => $khoaNN,
                'trinh_do_id' => $trinhDoTS,
                'mon_hoc_keywords' => ['Văn hóa', 'Lịch sử Nhật Bản', 'Nhật'],
                'ngay_vao_truong' => '2018-06-15',
            ],
            [
                'ma_giang_vien' => 'GV055',
                'ho_ten' => 'Phạm Thị Tuyết',
                'gioi_tinh' => 'Nữ',
                'ngay_sinh' => '1991-10-31',
                'dia_chi' => 'Hải Phòng',
                'email' => 'ptt.gv@university.edu.vn',
                'so_dien_thoai' => '0901234615',
                'khoa_id' => $khoaNN,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Kinh tế Nhật Bản', 'Nhật'],
                'ngay_vao_truong' => '2019-08-25',
            ],
            [
                'ma_giang_vien' => 'GV056',
                'ho_ten' => 'Hoàng Văn Uyên',
                'gioi_tinh' => 'Nam',
                'ngay_sinh' => '1988-12-09',
                'dia_chi' => 'Cần Thơ',
                'email' => 'hvu.gv@university.edu.vn',
                'so_dien_thoai' => '0901234616',
                'khoa_id' => $khoaNN,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Thương mại Trung Quốc', 'Trung'],
                'ngay_vao_truong' => '2017-03-20',
            ],
            [
                'ma_giang_vien' => 'GV057',
                'ho_ten' => 'Đỗ Thị Vân',
                'gioi_tinh' => 'Nữ',
                'ngay_sinh' => '1992-01-26',
                'dia_chi' => 'Hà Nội',
                'email' => 'dtv.gv@university.edu.vn',
                'so_dien_thoai' => '0901234617',
                'khoa_id' => $khoaNN,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Văn hóa Trung Quốc', 'Trung'],
                'ngay_vao_truong' => '2020-04-10',
            ],
            [
                'ma_giang_vien' => 'GV058',
                'ho_ten' => 'Vũ Văn Xuân',
                'gioi_tinh' => 'Nam',
                'ngay_sinh' => '1986-05-04',
                'dia_chi' => 'TP.HCM',
                'email' => 'vvx.gv@university.edu.vn',
                'so_dien_thoai' => '0901234618',
                'khoa_id' => $khoaNN,
                'trinh_do_id' => $trinhDoTS,
                'mon_hoc_keywords' => ['Tiếng Anh chuyên ngành', 'Anh'],
                'ngay_vao_truong' => '2015-11-05',
            ],
            [
                'ma_giang_vien' => 'GV059',
                'ho_ten' => 'Bùi Thị Yến',
                'gioi_tinh' => 'Nữ',
                'ngay_sinh' => '1989-07-21',
                'dia_chi' => 'Đà Nẵng',
                'email' => 'bty.gv@university.edu.vn',
                'so_dien_thoai' => '0901234619',
                'khoa_id' => $khoaNN,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Văn học nước ngoài', 'Văn học'],
                'ngay_vao_truong' => '2018-02-28',
            ],
            [
                'ma_giang_vien' => 'GV060',
                'ho_ten' => 'Ngô Văn An',
                'gioi_tinh' => 'Nam',
                'ngay_sinh' => '1990-09-07',
                'dia_chi' => 'Hải Phòng',
                'email' => 'nva2.gv@university.edu.vn',
                'so_dien_thoai' => '0901234620',
                'khoa_id' => $khoaNN,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Thực tập', 'Sư phạm', 'Phiên dịch'],
                'ngay_vao_truong' => '2019-07-15',
            ],
            [
                'ma_giang_vien' => 'GV061',
                'ho_ten' => 'Đinh Thị Bình',
                'gioi_tinh' => 'Nữ',
                'ngay_sinh' => '1991-11-23',
                'dia_chi' => 'Cần Thơ',
                'email' => 'dtb.gv@university.edu.vn',
                'so_dien_thoai' => '0901234621',
                'khoa_id' => $khoaNN,
                'trinh_do_id' => $trinhDoThS,
                'mon_hoc_keywords' => ['Khóa luận tốt nghiệp', 'Ngoại ngữ'],
                'ngay_vao_truong' => '2020-12-20',
            ],
        ];

        $count = 0;
        $totalMonHocAssigned = 0;

        foreach ($giangViens as $gvData) {
            // Tạo user trước
            $userId = DB::table('users')->insertGetId([
                'name' => $gvData['ho_ten'],
                'email' => $gvData['email'],
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ]);

            // Gán vai trò giảng viên cho user
            DB::table('tai_khoan_vai_tro')->insert([
                'tai_khoan_id' => $userId,
                'vai_tro_id' => $vaiTroGiangVien,
                'created_at' => now(),
                'updated_at' => now(),
            ]);

            // Tạo giảng viên
            $giangVienId = DB::table('giang_vien')->insertGetId([
                'user_id' => $userId,
                'ma_giang_vien' => $gvData['ma_giang_vien'],
                'ho_ten' => $gvData['ho_ten'],
                'gioi_tinh' => $gvData['gioi_tinh'] ?? null,
                'ngay_sinh' => $gvData['ngay_sinh'] ?? null,
                'dia_chi' => $gvData['dia_chi'] ?? null,
                'email' => $gvData['email'],
                'so_dien_thoai' => $gvData['so_dien_thoai'],
                'khoa_id' => $gvData['khoa_id'],
                'trinh_do_id' => $gvData['trinh_do_id'],
                'ngay_vao_truong' => $gvData['ngay_vao_truong'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);

            // Gán môn học cho giảng viên
            $monHocIds = $findMonHoc($gvData['mon_hoc_keywords']);
            if (!empty($monHocIds)) {
                foreach ($monHocIds as $monHocId) {
                    DB::table('giang_vien_mon_hoc')->insert([
                        'giang_vien_id' => $giangVienId,
                        'mon_hoc_id' => $monHocId,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]);
                }
                $totalMonHocAssigned += count($monHocIds);
            }

            $count++;
        }

        // Đếm số giảng viên theo khoa
        $countCNTT = DB::table('giang_vien')->where('khoa_id', $khoaCNTT)->count();
        $countKT = DB::table('giang_vien')->where('khoa_id', $khoaKT)->count();
        $countNN = DB::table('giang_vien')->where('khoa_id', $khoaNN)->count();

        echo "✅ Đã tạo {$count} giảng viên\n";
        echo "   👨‍🏫 Khoa CNTT: {$countCNTT} giảng viên\n";
        echo "   👨‍🏫 Khoa Kinh tế: {$countKT} giảng viên\n";
        echo "   👨‍🏫 Khoa Ngoại ngữ: {$countNN} giảng viên\n";
        echo "   📚 Đã gán {$totalMonHocAssigned} môn học cho các giảng viên\n";
        echo "   🔑 Mật khẩu mặc định: password\n";
    }
}
