<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MonHocSeeder extends Seeder
{
    public function run(): void
    {
        // Lấy ID của Khoa Công nghệ thông tin (giả sử là khoa đầu tiên)
        $khoaCNTT = DB::table('khoa')->where('ten_khoa', 'like', '%Công nghệ thông tin%')->first();
        $khoaKinhTe = DB::table('khoa')->where('ten_khoa', 'like', '%Kinh tế%')->first();

        $khoaCNTT_id = $khoaCNTT ? $khoaCNTT->id : DB::table('khoa')->first()->id;
        $khoaKinhTe_id = $khoaKinhTe ? $khoaKinhTe->id : DB::table('khoa')->skip(1)->first()->id;

        $monHocs = [
            // ===== MÔN ĐẠI CƯƠNG =====
            [
                'ma_mon' => 'DC001',
                'ten_mon' => 'Triết học Mác - Lênin',
                'so_tin_chi' => 3,
                'so_tin_chi_ly_thuyet' => 2,
                'so_tin_chi_thuc_hanh' => 1,
                'mo_ta' => 'Những nguyên lý cơ bản của chủ nghĩa Mác - Lênin',
                'loai_mon' => 'dai_cuong',
                'khoa_id' => $khoaCNTT_id,
                'hinh_thuc_day' => 'offline',
                'thoi_luong_hoc' => 45,
                'so_buoi_hoc' => 15,
            ],
            [
                'ma_mon' => 'DC002',
                'ten_mon' => 'Kinh tế chính trị Mác - Lênin',
                'so_tin_chi' => 2,
                'so_tin_chi_ly_thuyet' => 2,
                'so_tin_chi_thuc_hanh' => 0,
                'mo_ta' => 'Những vấn đề cơ bản về kinh tế chính trị',
                'loai_mon' => 'dai_cuong',
                'khoa_id' => $khoaCNTT_id,
                'hinh_thuc_day' => 'offline',
                'thoi_luong_hoc' => 30,
                'so_buoi_hoc' => 10,
            ],
            [
                'ma_mon' => 'DC003',
                'ten_mon' => 'Chủ nghĩa xã hội khoa học',
                'so_tin_chi' => 2,
                'so_tin_chi_ly_thuyet' => 2,
                'so_tin_chi_thuc_hanh' => 0,
                'mo_ta' => 'Lịch sử hình thành và phát triển của chủ nghĩa xã hội',
                'loai_mon' => 'dai_cuong',
                'khoa_id' => $khoaCNTT_id,
                'hinh_thuc_day' => 'online',
                'thoi_luong_hoc' => 30,
                'so_buoi_hoc' => 10,
            ],
            [
                'ma_mon' => 'DC004',
                'ten_mon' => 'Lịch sử Đảng Cộng sản Việt Nam',
                'so_tin_chi' => 2,
                'so_tin_chi_ly_thuyet' => 2,
                'so_tin_chi_thuc_hanh' => 0,
                'mo_ta' => 'Quá trình lãnh đạo cách mạng của Đảng Cộng sản Việt Nam',
                'loai_mon' => 'dai_cuong',
                'khoa_id' => $khoaCNTT_id,
                'hinh_thuc_day' => 'offline',
                'thoi_luong_hoc' => 30,
                'so_buoi_hoc' => 10,
            ],
            [
                'ma_mon' => 'DC005',
                'ten_mon' => 'Tư tưởng Hồ Chí Minh',
                'so_tin_chi' => 2,
                'so_tin_chi_ly_thuyet' => 2,
                'so_tin_chi_thuc_hanh' => 0,
                'mo_ta' => 'Hệ thống quan điểm toàn diện và sâu sắc về những vấn đề cơ bản của cách mạng Việt Nam',
                'loai_mon' => 'dai_cuong',
                'khoa_id' => $khoaCNTT_id,
                'hinh_thuc_day' => 'offline',
                'thoi_luong_hoc' => 30,
                'so_buoi_hoc' => 10,
            ],
            [
                'ma_mon' => 'DC006',
                'ten_mon' => 'Pháp luật đại cương',
                'so_tin_chi' => 2,
                'so_tin_chi_ly_thuyet' => 2,
                'so_tin_chi_thuc_hanh' => 0,
                'mo_ta' => 'Những kiến thức cơ bản về nhà nước và pháp luật',
                'loai_mon' => 'dai_cuong',
                'khoa_id' => $khoaCNTT_id,
                'hinh_thuc_day' => 'offline',
                'thoi_luong_hoc' => 30,
                'so_buoi_hoc' => 10,
            ],
            [
                'ma_mon' => 'DC007',
                'ten_mon' => 'Tiếng Anh 1',
                'so_tin_chi' => 3,
                'so_tin_chi_ly_thuyet' => 1,
                'so_tin_chi_thuc_hanh' => 2,
                'mo_ta' => 'Kiến thức ngoại ngữ cơ bản - Trình độ A1',
                'loai_mon' => 'dai_cuong',
                'khoa_id' => $khoaCNTT_id,
                'hinh_thuc_day' => 'hybrid',
                'thoi_luong_hoc' => 45,
                'so_buoi_hoc' => 15,
            ],
            [
                'ma_mon' => 'DC008',
                'ten_mon' => 'Tiếng Anh 2',
                'so_tin_chi' => 3,
                'so_tin_chi_ly_thuyet' => 1,
                'so_tin_chi_thuc_hanh' => 2,
                'mo_ta' => 'Kiến thức ngoại ngữ cơ bản - Trình độ A2',
                'loai_mon' => 'dai_cuong',
                'khoa_id' => $khoaCNTT_id,
                'hinh_thuc_day' => 'hybrid',
                'thoi_luong_hoc' => 45,
                'so_buoi_hoc' => 15,
            ],
            [
                'ma_mon' => 'DC009',
                'ten_mon' => 'Giáo dục thể chất 1',
                'so_tin_chi' => 1,
                'so_tin_chi_ly_thuyet' => 0,
                'so_tin_chi_thuc_hanh' => 1,
                'mo_ta' => 'Rèn luyện sức khỏe cơ bản',
                'loai_mon' => 'dai_cuong',
                'khoa_id' => $khoaCNTT_id,
                'hinh_thuc_day' => 'offline',
                'thoi_luong_hoc' => 15,
                'so_buoi_hoc' => 15,
            ],
            [
                'ma_mon' => 'DC010',
                'ten_mon' => 'Giáo dục thể chất 2',
                'so_tin_chi' => 1,
                'so_tin_chi_ly_thuyet' => 0,
                'so_tin_chi_thuc_hanh' => 1,
                'mo_ta' => 'Rèn luyện sức khỏe nâng cao',
                'loai_mon' => 'dai_cuong',
                'khoa_id' => $khoaCNTT_id,
                'hinh_thuc_day' => 'offline',
                'thoi_luong_hoc' => 15,
                'so_buoi_hoc' => 15,
            ],

            // ===== MÔN CƠ SỞ NGÀNH CNTT =====
            [
                'ma_mon' => 'IT101',
                'ten_mon' => 'Nhập môn lập trình',
                'so_tin_chi' => 3,
                'so_tin_chi_ly_thuyet' => 2,
                'so_tin_chi_thuc_hanh' => 1,
                'mo_ta' => 'Kiến thức lập trình cơ bản với ngôn ngữ C/C++',
                'loai_mon' => 'co_so_nganh',
                'khoa_id' => $khoaCNTT_id,
                'hinh_thuc_day' => 'offline',
                'thoi_luong_hoc' => 45,
                'so_buoi_hoc' => 15,
            ],
            [
                'ma_mon' => 'IT102',
                'ten_mon' => 'Cấu trúc dữ liệu và giải thuật',
                'so_tin_chi' => 3,
                'so_tin_chi_ly_thuyet' => 2,
                'so_tin_chi_thuc_hanh' => 1,
                'mo_ta' => 'Các cấu trúc dữ liệu cơ bản: danh sách, stack, queue, tree, graph',
                'loai_mon' => 'co_so_nganh',
                'khoa_id' => $khoaCNTT_id,
                'hinh_thuc_day' => 'offline',
                'thoi_luong_hoc' => 45,
                'so_buoi_hoc' => 15,
            ],
            [
                'ma_mon' => 'IT103',
                'ten_mon' => 'Lập trình hướng đối tượng',
                'so_tin_chi' => 3,
                'so_tin_chi_ly_thuyet' => 2,
                'so_tin_chi_thuc_hanh' => 1,
                'mo_ta' => 'Các khái niệm OOP: class, object, inheritance, polymorphism',
                'loai_mon' => 'co_so_nganh',
                'khoa_id' => $khoaCNTT_id,
                'hinh_thuc_day' => 'offline',
                'thoi_luong_hoc' => 45,
                'so_buoi_hoc' => 15,
            ],
            [
                'ma_mon' => 'IT104',
                'ten_mon' => 'Cơ sở dữ liệu',
                'so_tin_chi' => 3,
                'so_tin_chi_ly_thuyet' => 2,
                'so_tin_chi_thuc_hanh' => 1,
                'mo_ta' => 'Thiết kế cơ sở dữ liệu quan hệ, SQL, normalization',
                'loai_mon' => 'co_so_nganh',
                'khoa_id' => $khoaCNTT_id,
                'hinh_thuc_day' => 'offline',
                'thoi_luong_hoc' => 45,
                'so_buoi_hoc' => 15,
            ],
            [
                'ma_mon' => 'IT105',
                'ten_mon' => 'Hệ điều hành',
                'so_tin_chi' => 3,
                'so_tin_chi_ly_thuyet' => 2,
                'so_tin_chi_thuc_hanh' => 1,
                'mo_ta' => 'Nguyên lý hoạt động của hệ điều hành Windows, Linux',
                'loai_mon' => 'co_so_nganh',
                'khoa_id' => $khoaCNTT_id,
                'hinh_thuc_day' => 'offline',
                'thoi_luong_hoc' => 45,
                'so_buoi_hoc' => 15,
            ],
            [
                'ma_mon' => 'IT106',
                'ten_mon' => 'Mạng máy tính',
                'so_tin_chi' => 3,
                'so_tin_chi_ly_thuyet' => 2,
                'so_tin_chi_thuc_hanh' => 1,
                'mo_ta' => 'Các giao thức mạng, mô hình OSI, TCP/IP',
                'loai_mon' => 'co_so_nganh',
                'khoa_id' => $khoaCNTT_id,
                'hinh_thuc_day' => 'offline',
                'thoi_luong_hoc' => 45,
                'so_buoi_hoc' => 15,
            ],

            // ===== MÔN CHUYÊN NGÀNH BẮT BUỘC CNTT =====
            [
                'ma_mon' => 'IT201',
                'ten_mon' => 'Phát triển ứng dụng Web',
                'so_tin_chi' => 3,
                'so_tin_chi_ly_thuyet' => 2,
                'so_tin_chi_thuc_hanh' => 1,
                'mo_ta' => 'HTML, CSS, JavaScript, PHP/Laravel cơ bản',
                'loai_mon' => 'chuyen_nganh_bat_buoc',
                'khoa_id' => $khoaCNTT_id,
                'hinh_thuc_day' => 'offline',
                'thoi_luong_hoc' => 45,
                'so_buoi_hoc' => 15,
            ],
            [
                'ma_mon' => 'IT202',
                'ten_mon' => 'Lập trình ứng dụng di động',
                'so_tin_chi' => 3,
                'so_tin_chi_ly_thuyet' => 2,
                'so_tin_chi_thuc_hanh' => 1,
                'mo_ta' => 'Phát triển ứng dụng Android, iOS với Flutter/React Native',
                'loai_mon' => 'chuyen_nganh_bat_buoc',
                'khoa_id' => $khoaCNTT_id,
                'hinh_thuc_day' => 'offline',
                'thoi_luong_hoc' => 45,
                'so_buoi_hoc' => 15,
            ],
            [
                'ma_mon' => 'IT203',
                'ten_mon' => 'Công nghệ phần mềm',
                'so_tin_chi' => 3,
                'so_tin_chi_ly_thuyet' => 2,
                'so_tin_chi_thuc_hanh' => 1,
                'mo_ta' => 'Quy trình phát triển phần mềm, Agile, Scrum',
                'loai_mon' => 'chuyen_nganh_bat_buoc',
                'khoa_id' => $khoaCNTT_id,
                'hinh_thuc_day' => 'offline',
                'thoi_luong_hoc' => 45,
                'so_buoi_hoc' => 15,
            ],
            [
                'ma_mon' => 'IT204',
                'ten_mon' => 'Trí tuệ nhân tạo',
                'so_tin_chi' => 3,
                'so_tin_chi_ly_thuyet' => 2,
                'so_tin_chi_thuc_hanh' => 1,
                'mo_ta' => 'Machine Learning cơ bản, Neural Network',
                'loai_mon' => 'chuyen_nganh_bat_buoc',
                'khoa_id' => $khoaCNTT_id,
                'hinh_thuc_day' => 'hybrid',
                'thoi_luong_hoc' => 45,
                'so_buoi_hoc' => 15,
            ],
            [
                'ma_mon' => 'IT205',
                'ten_mon' => 'An toàn và bảo mật thông tin',
                'so_tin_chi' => 3,
                'so_tin_chi_ly_thuyet' => 2,
                'so_tin_chi_thuc_hanh' => 1,
                'mo_ta' => 'Mã hóa, xác thực, tường lửa, phát hiện xâm nhập',
                'loai_mon' => 'chuyen_nganh_bat_buoc',
                'khoa_id' => $khoaCNTT_id,
                'hinh_thuc_day' => 'offline',
                'thoi_luong_hoc' => 45,
                'so_buoi_hoc' => 15,
            ],

            // ===== MÔN CHUYÊN NGÀNH TỰ CHỌN CNTT =====
            [
                'ma_mon' => 'IT301',
                'ten_mon' => 'Xử lý ảnh số',
                'so_tin_chi' => 3,
                'so_tin_chi_ly_thuyet' => 2,
                'so_tin_chi_thuc_hanh' => 1,
                'mo_ta' => 'Các kỹ thuật xử lý ảnh với OpenCV, Python',
                'loai_mon' => 'chuyen_nganh_tu_chon',
                'khoa_id' => $khoaCNTT_id,
                'hinh_thuc_day' => 'offline',
                'thoi_luong_hoc' => 45,
                'so_buoi_hoc' => 15,
            ],
            [
                'ma_mon' => 'IT302',
                'ten_mon' => 'Khoa học dữ liệu',
                'so_tin_chi' => 3,
                'so_tin_chi_ly_thuyet' => 2,
                'so_tin_chi_thuc_hanh' => 1,
                'mo_ta' => 'Big Data, Data Mining, Data Visualization',
                'loai_mon' => 'chuyen_nganh_tu_chon',
                'khoa_id' => $khoaCNTT_id,
                'hinh_thuc_day' => 'hybrid',
                'thoi_luong_hoc' => 45,
                'so_buoi_hoc' => 15,
            ],
            [
                'ma_mon' => 'IT303',
                'ten_mon' => 'Lập trình game',
                'so_tin_chi' => 3,
                'so_tin_chi_ly_thuyet' => 1,
                'so_tin_chi_thuc_hanh' => 2,
                'mo_ta' => 'Phát triển game với Unity, Unreal Engine',
                'loai_mon' => 'chuyen_nganh_tu_chon',
                'khoa_id' => $khoaCNTT_id,
                'hinh_thuc_day' => 'offline',
                'thoi_luong_hoc' => 45,
                'so_buoi_hoc' => 15,
            ],
            [
                'ma_mon' => 'IT304',
                'ten_mon' => 'Internet of Things (IoT)',
                'so_tin_chi' => 3,
                'so_tin_chi_ly_thuyet' => 2,
                'so_tin_chi_thuc_hanh' => 1,
                'mo_ta' => 'Arduino, Raspberry Pi, cảm biến, kết nối mạng',
                'loai_mon' => 'chuyen_nganh_tu_chon',
                'khoa_id' => $khoaCNTT_id,
                'hinh_thuc_day' => 'offline',
                'thoi_luong_hoc' => 45,
                'so_buoi_hoc' => 15,
            ],
            [
                'ma_mon' => 'IT305',
                'ten_mon' => 'Blockchain và ứng dụng',
                'so_tin_chi' => 3,
                'so_tin_chi_ly_thuyet' => 2,
                'so_tin_chi_thuc_hanh' => 1,
                'mo_ta' => 'Smart Contract, Ethereum, DApp',
                'loai_mon' => 'chuyen_nganh_tu_chon',
                'khoa_id' => $khoaCNTT_id,
                'hinh_thuc_day' => 'online',
                'thoi_luong_hoc' => 45,
                'so_buoi_hoc' => 15,
            ],

            // ===== MÔN THỰC TẬP & ĐỒ ÁN =====
            [
                'ma_mon' => 'IT401',
                'ten_mon' => 'Thực tập doanh nghiệp',
                'so_tin_chi' => 4,
                'so_tin_chi_ly_thuyet' => 0,
                'so_tin_chi_thuc_hanh' => 4,
                'mo_ta' => 'Thực tập tại doanh nghiệp ít nhất 4 tuần',
                'loai_mon' => 'thuc_tap',
                'khoa_id' => $khoaCNTT_id,
                'hinh_thuc_day' => 'offline',
                'thoi_luong_hoc' => 60,
                'so_buoi_hoc' => 20,
            ],
            [
                'ma_mon' => 'IT402',
                'ten_mon' => 'Đồ án tốt nghiệp',
                'so_tin_chi' => 10,
                'so_tin_chi_ly_thuyet' => 2,
                'so_tin_chi_thuc_hanh' => 8,
                'mo_ta' => 'Thực hiện đồ án tốt nghiệp theo chuyên ngành',
                'loai_mon' => 'do_an_tot_nghiep',
                'khoa_id' => $khoaCNTT_id,
                'hinh_thuc_day' => 'hybrid',
                'thoi_luong_hoc' => 150,
                'so_buoi_hoc' => 30,
            ],

            // ===== MÔN CƠ BẢN KHOA KINH TẾ =====
            [
                'ma_mon' => 'EC101',
                'ten_mon' => 'Kinh tế vi mô',
                'so_tin_chi' => 3,
                'so_tin_chi_ly_thuyet' => 3,
                'so_tin_chi_thuc_hanh' => 0,
                'mo_ta' => 'Các nguyên lý cơ bản của kinh tế vi mô',
                'loai_mon' => 'co_so_nganh',
                'khoa_id' => $khoaKinhTe_id,
                'hinh_thuc_day' => 'offline',
                'thoi_luong_hoc' => 45,
                'so_buoi_hoc' => 15,
            ],
            [
                'ma_mon' => 'EC102',
                'ten_mon' => 'Kinh tế vĩ mô',
                'so_tin_chi' => 3,
                'so_tin_chi_ly_thuyet' => 3,
                'so_tin_chi_thuc_hanh' => 0,
                'mo_ta' => 'Các nguyên lý cơ bản của kinh tế vĩ mô',
                'loai_mon' => 'co_so_nganh',
                'khoa_id' => $khoaKinhTe_id,
                'hinh_thuc_day' => 'offline',
                'thoi_luong_hoc' => 45,
                'so_buoi_hoc' => 15,
            ],
            [
                'ma_mon' => 'EC103',
                'ten_mon' => 'Quản trị học',
                'so_tin_chi' => 3,
                'so_tin_chi_ly_thuyet' => 2,
                'so_tin_chi_thuc_hanh' => 1,
                'mo_ta' => 'Các chức năng quản trị cơ bản trong doanh nghiệp',
                'loai_mon' => 'co_so_nganh',
                'khoa_id' => $khoaKinhTe_id,
                'hinh_thuc_day' => 'offline',
                'thoi_luong_hoc' => 45,
                'so_buoi_hoc' => 15,
            ],
            [
                'ma_mon' => 'EC104',
                'ten_mon' => 'Marketing căn bản',
                'so_tin_chi' => 3,
                'so_tin_chi_ly_thuyet' => 2,
                'so_tin_chi_thuc_hanh' => 1,
                'mo_ta' => 'Các khái niệm cơ bản về marketing, 4P',
                'loai_mon' => 'chuyen_nganh_bat_buoc',
                'khoa_id' => $khoaKinhTe_id,
                'hinh_thuc_day' => 'offline',
                'thoi_luong_hoc' => 45,
                'so_buoi_hoc' => 15,
            ],
        ];

        foreach ($monHocs as $monHoc) {
            DB::table('mon_hoc')->insert(array_merge($monHoc, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
